server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chatserver
    username: chatserver
    password: chatserver
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: localhost
      port: 6379
