CREATE TABLE IF NOT EXISTS chat_room (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    created_by      VARCHAR(255) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL,
    closed_at       TIMESTAMPTZ NULL,
    last_message_at TIMESTAMPTZ NULL
);

CREATE TABLE IF NOT EXISTS chat_room_member (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_room_id BIGINT NOT NULL,
    user_id      VARCHAR(255) NOT NULL,
    joined_at    TIMESTAMPTZ NOT NULL,
    left_at      TIMESTAMPTZ NULL,
    CONSTRAINT fk_chat_room_member_room
        FOREIGN KEY (chat_room_id) REFERENCES chat_room(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_chat_room_member_active
ON chat_room_member (chat_room_id, user_id)
WHERE left_at IS NULL;

CREATE INDEX IF NOT EXISTS ix_chat_room_member_active_by_user
ON chat_room_member (user_id)
WHERE left_at IS NULL;
